name: Build Fava Container Image

on:
  schedule:
    - cron: "0 4 * * 0" # Every Sunday at 04:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Fava Docker Image
        uses: docker/build-push-action@v4
        id: build_image
        with:
          push: true
          load: false
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/fava:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/fava:latest
          cache-to: type=inline
          context: ./fava

      - name: push docker image
        run: |
          OUTPUT=$(docker run --rm ghcr.io/mruoss/fava:latest fava --version 2> /dev/null)
          VERSION=${OUTPUT#"fava, version "}
          docker buildx imagetools create ghcr.io/${{ github.repository_owner }}/fava:latest -t ghcr.io/${{ github.repository_owner }}/fava:$VERSION
