name: Build Fava Container Image

on:
  schedule:
    - cron: "0 4 * * 0" # Every Sunday at 04:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: get latest tags
        id: versions
        run: |
          LATEST=$(cd fava && git describe --abbrev=0 --tags)
          echo "latest=$LATEST" >> "$GITHUB_OUTPUT"

      - name: Build E2E Image
        uses: docker/build-push-action@v4
        id: build_and_push_e2e
        with:
          push: true
          load: false
          platforms: linux/amd64,linux/arm64/v8,linux/arm
          tags: ghcr.io/${{ github.actor }}/fava:${{ steps.versions.outputs.latest }},ghcr.io/${{ github.repository_owner }}/fava:latest
          cache-from: type=registry,ref=latest
          cache-to: type=inline
          context: ./fava/contrib/docker
